### ISSUE TITLE
Getting wrong country result

### ISSUE THREAD

**Issue by meetmrkoushik** [malyw/malyw.github.io#13]
Trying to filter country Oman and getting Romania
https://corona.lmao.ninja/countries/oman

**Comment by malyw** [comment]
Not sure, can you provide more details what is the issue about?

**Comment by meetmrkoushik** [comment]
https://corona.lmao.ninja/countries/
Response : {"country":"Oman","countryInfo":{"_id":512,"iso2":"OM","iso3":"OMN","lat":21,"long":57,"flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/om.png"},"cases":231,"todayCases":21,"deaths":1,"todayDeaths":0,"recovered":57,"active":173,"critical":3,"casesPerOneMillion":45,"deathsPerOneMillion":0.2,"updated":1585853874745},

https://corona.lmao.ninja/countries/Oman
Response: {"country":"Romania","countryInfo":{"_id":642,"iso2":"RO","iso3":"ROU","lat":46,"long":25,"flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ro.png"},"cases":2738,"todayCases":278,"deaths":114,"todayDeaths":22,"recovered":267,"active":2357,"critical":78,"casesPerOneMillion":142,"deathsPerOneMillion":6,"updated":1585853874737}

https://corona.lmao.ninja/countries  [Getting "cases":231,"]
https://corona.lmao.ninja/countries/Oman [ Getting cases":2738,"]

Once I'm trying to filter using country then getting different cases.

**Comment by malyw** [comment]
Ok, I mean how is it related to https://github.com/malyw/malyw.github.io/ ?
